# Generated by Django 3.0.4 on 2020-04-10 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorspacemodel',
            name='id',
            field=models.DateTimeField(default=datetime.date.today, primary_key=True, serialize=False),
        ),
    ]
